apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
  namespace: default
data:
  envoy.yaml: |
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901
    node:
      id: "publisher"
      cluster: "rpi-edge"

    static_resources:
      listeners:
      - name: mqtt
        address:
          socket_address:
            address: 127.0.0.1
            port_value: 1883
        filter_chains:
        - filters:
          - name: envoy.filters.network.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: ingress_tcp
              cluster: mqtt_broker
      clusters:
      - name: spire_agent
        connect_timeout: 0.25s
        http2_protocol_options: {}
        load_assignment:	
          cluster_name: spire_agent
          endpoints:	
          - lb_endpoints:	
            - endpoint:	
                address:	
                  pipe:	
                    path: /run/spire/sockets/agent.sock
      - name: mqtt_broker
        connect_timeout: 5s
        type: strict_dns
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: mqtt_broker
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 10.10.10.10
                    port_value: 443
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
            common_tls_context:
              tls_certificate_sds_secret_configs:
              - name: "spiffe://rpi.edge/ns/default/sa/serviceaccount-publisher/publisher"
                sds_config:
                  api_config_source:
                    api_type: GRPC
                    grpc_services:
                      envoy_grpc:
                        cluster_name: spire_agent
                    transport_api_version: V3
                  resource_api_version: V3                                              
              combined_validation_context:
                default_validation_context:
                  match_subject_alt_names:
                    exact: "spiffe://azure.cloud/ns/default/sa/serviceaccount-broker/broker"
                validation_context_sds_secret_config:
                  name: "spiffe://azure.cloud"
                  sds_config:
                    api_config_source:
                      api_type: GRPC
                      grpc_services:
                        envoy_grpc:
                          cluster_name: spire_agent
                      transport_api_version: V3
                    resource_api_version: V3                          
              tls_params:
                ecdh_curves:
                  - X25519:P-256:P-521:P-384
