apiVersion: v1
kind: ServiceAccount
metadata:
  name: serviceaccount-publisher
  labels:
    account: publisher
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher-v1
  labels:
    app: publisher
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
     app: publisher
     version: v1
  template:
    metadata:
      labels:
        app: publisher
        version: v1
    spec:
      serviceAccount: serviceaccount-publisher
      containers:
      - name: publisher
        securityContext:
          privileged: true
        image: cloudical/publisher@sha256:4f7b14a916c7896f5150eb124b8ff3967129f9690ac93e3dfce94ca84bfd2702
        imagePullPolicy: Always
        env:
          - name: BROKER_HOST
            value: localhost
          - name: BROKER_PORT
            value: "1883"
        volumeMounts:
        - mountPath: /dev/ttyACM0
          name: ttyacm0
        - mountPath: /dev/ttyACM1
          name: ttyacm1
      - name: envoy
        image: docker.io/envoyproxy/envoy:v1.20-latest
        args: ["-l", "debug", "--local-address-ip-version", "v4", "-c", "/run/envoy/envoy.yaml", "--base-id", "1"]
        volumeMounts:
        - name: envoy-config
          mountPath: "/run/envoy"
          readOnly: true 
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true 
      nodeSelector:
        kubernetes.io/hostname: k8s-worker-01
      volumes:
        - name: ttyacm0
          hostPath:
            path: /dev/ttyACM0
        - name: ttyacm1
          hostPath:
            path: /dev/ttyACM1
        - name: envoy-config
          configMap:
            name: envoy-config
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
