apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-conf
data:
  telegraf.conf: |+
    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_jitter = "0s"
      debug = false
      quiet = false
      hostname = ""
      omit_hostname = true
    [[outputs.influxdb]]
      urls = ["http://influxdb:8086"]
      database = "dht"
      retention_policy = "autogen"
      precision = "s"
      timeout = "5s"
    [[outputs.file]]
    files = ["stdout"]
    data_format = "influx"
    [[inputs.mqtt_consumer]]
      servers = ["tcp://broker-lb:1883"]
      qos = 0
      topics = [
        "rpi/sensor1","rpi/sensor2"
      ]
      insecure_skip_verify = true
      client_id = ""
      data_format = "json"
      name_override = "dht"
      tag_keys = ["deviceID"]
      json_string_fields = ["humidity","tempeture","heat_index"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: telegraf:1.14-alpine
        ports:
        - name: udp
          protocol: UDP
          containerPort: 8092
        - name: http
          containerPort: 8186
        volumeMounts:
        - name: config
          mountPath: /etc/telegraf
        resources:
          requests:
            cpu: 50m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi
      volumes:
      - name: config
        configMap:
          name: telegraf-conf
